# Generated by Django 5.2.5 on 2025-08-13 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='subject1_marks',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='subject2_marks',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='subject3_marks',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='subject4_marks',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='subject5_marks',
            field=models.IntegerField(default=0),
        ),
    ]
