# Generated by Django 5.2.5 on 2025-08-13 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_student_subject1_marks_student_subject2_marks_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='subject1_marks',
            new_name='CD',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='subject2_marks',
            new_name='DAA',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='subject3_marks',
            new_name='DWDM',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='subject4_marks',
            new_name='IoT',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='subject5_marks',
            new_name='OOAD',
        ),
    ]
