# Generated by Django 5.2.5 on 2025-08-16 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_rename_subject1_marks_student_cd_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='CD',
            field=models.IntegerField(default=0, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='DAA',
            field=models.IntegerField(blank=True, default=0, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='DWDM',
            field=models.IntegerField(blank=True, default=0, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='IoT',
            field=models.IntegerField(blank=True, default=0, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='OOAD',
            field=models.IntegerField(blank=True, default=0, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='grade',
            unique_together={('student', 'subject')},
        ),
    ]
