# Generated by Django 5.2.5 on 2025-09-05 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_alter_attendance_unique_together_alter_student_cd_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grade',
            name='marks',
        ),
        migrations.AddField(
            model_name='grade',
            name='exam_type',
            field=models.CharField(choices=[('mid1', 'Mid 1'), ('mid2', 'Mid 2'), ('final', 'Final Exam')], default='mid1', max_length=10),
        ),
    ]
