# Generated by Django 5.2.5 on 2025-09-05 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0006_remove_grade_marks_grade_exam_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='marks',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
