# Generated by Django 5.2.5 on 2025-09-05 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0007_grade_marks'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='grade',
            unique_together={('student', 'subject', 'exam_type')},
        ),
    ]
